<?php

namespace OCUserBundle\Repository;

/**
 * ficheInscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ficheInscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
