<?php

namespace OCUserBundle\Repository;

/**
 * TypeCompetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCompetRepository extends \Doctrine\ORM\EntityRepository
{
}
